name: Lighthouse Audit - Live Site

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://www.lloydsibson.com
            https://www.lloydsibson.com/about
            https://www.lloydsibson.com/portfolio
            https://www.lloydsibson.com/contact
          temporaryPublicStorage: true
          uploadArtifacts: true
          runs: 1
          budgetPath: "./budget.json" # Optional: Define performance budgets
