name: Lighthouse Audit - Live Site

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse Audit on Desktop
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://lloydsibson.com
            https://lloydsibson.com/about
            https://lloydsibson.com/portfolio
            https://lloydsibson.com/contact
          temporaryPublicStorage: true
          uploadArtifacts: true
          runs: 1
          configPath: "../../lighthouse-desktop-config.js" # Path to desktop config

      - name: Run Lighthouse Audit on Mobile
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://lloydsibson.com
            https://lloydsibson.com/about
            https://lloydsibson.com/portfolio
            https://lloydsibson.com/contact
          temporaryPublicStorage: true
          uploadArtifacts: true
          runs: 1
          configPath: "../../lighthouse-mobile-config.js" # Path to mobile config
