name: CI
on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install

      - name: lighthouse mobile audit
        run: npm run lhci:mobile

      - name: lighthouse desktop audit
        run: npm run lhci:desktop
        