name: CI/CD Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [development, production]
  pull_request:
    branches: [development, production]

jobs:
  # Unit-Tests:
  #   if: github.ref == 'refs/heads/development'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Run tests
  #       run: npm test

  Deploy-Development:
    #   needs: Unit-Tests
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  # Lighthouse-Tests:
  #   needs: Deploy-Development
  #   if: github.ref == 'refs/heads/development'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Lighthouse Performance Check
  #       uses: treosh/lighthouse-ci-action@v9
  #       with:
  #         urls: |
  #           "https://lloydsibson-com-nxt-app-git-dev-b0ca1c-lloyds-projects-6664c418.vercel.app"
  #           "https://lloydsibson-com-nxt-app-git-dev-b0ca1c-lloyds-projects-6664c418.vercel.app/about"
  #           "https://lloydsibson-com-nxt-app-git-dev-b0ca1c-lloyds-projects-6664c418.vercel.app/portfolio"
  #           "https://lloydsibson-com-nxt-app-git-dev-b0ca1c-lloyds-projects-6664c418.vercel.app/contact"
  #         configPath: ".github/workflows/lighthouserc.json"
  #

  Merge-Dev-to-Prod:
    needs: Deploy-Development
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git User Info
        run: |
          git config user.email "lloydsibson@gmail.com"
          git config user.name "Lloyd Sibson"
      - name: Fetch all branches
        run: git fetch --all

      - name: Merge Dev -> Prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: production
          message: Merge development into production
          github_token: ${{ secrets.GITHUB_TOKEN }}

  Deploy-Production:
    needs: Merge-Dev-to-Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "production" # Ensure it checks out the production branch
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
