name: CI/CD Pipeline

on:
  push:
    branches: [production, development]
  pull_request:
    branches: [production, development]

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  Deploy:
    needs: Unit-Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm i -g vercel
      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/production'
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        env:
          CI: true
      - name: Deploy to Vercel (Development)
        if: github.ref == 'refs/heads/development'
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm
        env:
          CI: true
