name: CI/CD Pipeline

on:
  push:
    branches: [production, development]
  pull_request:
    branches: [production, development]

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  Check-Files:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: ls -la

  Lighthouse-Check:
    needs: Unit-Tests
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lighthouse Performance Check
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            "https://lloydsibson-com-nxt-app-git-dev-b0ca1c-lloyds-projects-6664c418.vercel.app"
            "https://lloydsibson-com-nxt-app-git-dev-b0ca1c-lloyds-projects-6664c418.vercel.app/about"
            "https://lloydsibson-com-nxt-app-git-dev-b0ca1c-lloyds-projects-6664c418.vercel.app/portfolio"
            "https://lloydsibson-com-nxt-app-git-dev-b0ca1c-lloyds-projects-6664c418.vercel.app/contact"
          configPath: "./lighthouserc.json"
          temporaryPublicStorage: true
          uploadArtifacts: true
          runs: 3

  Deploy-Production:
    needs: Lighthouse-Check
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm i -g vercel
      - name: Deploy to Vercel (Production)
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        env:
          CI: true
