name: CI/CD Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [development, production]
  pull_request:
    branches: [development, production]
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00 every Sunday

jobs:
  Unit-Tests:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git User Info
        run: |
          git config user.email "lloydsibson@gmail.com"
          git config user.name "Lloyd Sibson"
      - name: Update NPM Packages
        run: |
          npm update
          git add .
          git commit -m "Update npm packages" || echo "No changes to commit"
          git push
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  Deploy-Preview:
    needs: Unit-Tests
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  Lighthouse-Tests:
    needs: Deploy-Preview
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lighthouse Performance Check
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            "https://lloydsibson-com-nxt-app.vercel.app"
            "https://lloydsibson-com-nxt-app.vercel.app/about"
            "https://lloydsibson-com-nxt-app.vercel.app/portfolio"
            "https://lloydsibson-com-nxt-app.vercel.app/contact"
          configPath: ".github/workflows/lighthouserc.json"
          temporaryPublicStorage: true
          uploadArtifacts: true

  Merge-Dev-to-Prod:
    needs: Lighthouse-Tests
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git User Info
        run: |
          git config user.email "lloydsibson@gmail.com"
          git config user.name "Lloyd Sibson"
      - name: Fetch all branches
        run: git fetch --all
      - name: Merge Dev -> Prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: production
          message: Merge Development into Production
          github_token: ${{ secrets.GITHUB_TOKEN }}

  Deploy-Production:
    needs: Merge-Dev-to-Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "production" # Ensure it checks out the production branch
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
